Update README.md
hs3city/ordinal-scale-stats-py pull request #26
Opened 2023-07-13 14:48 UTC by SimonMolinsky

Please check how does it sound? Should I add other headers? Are there typos, ...

2023-07-13 15:17 UTC, Reckony commented
LGTM :boom:

2023-07-13 15:17 UTC, Reckony submitted a review, later dismissed

2023-07-13 19:24 UTC, fgrabowski requested changes
However, I am not an english teacher so I may be wrong at some points, but there are also points that I am sure of

2023-07-13 19:24 UTC, fgrabowski commented on README.md
> +Classical measurements of central tendency do not fit well ordinal data [ADD BIBLIOGRAPHY]. That's why we encourage you to use `ordinal-scale-stats` package for your analysis of survey responses.
I believe that there should be "do not fit well WITH ..."

2023-07-13 19:24 UTC, fgrabowski commented on README.md
> +Classical measurements of central tendency do not fit well ordinal data [ADD BIBLIOGRAPHY]. That's why we encourage you to use `ordinal-scale-stats` package for your analysis of survey responses.
Also, "That's why we encourage you to use THE `ordinal-scale-stats` package for your analysis of survey responses."

2023-07-13 19:24 UTC, fgrabowski commented on README.md
> +Usually, a survey output is placed on the Likert scale, where answers are ordered to describe person's feelings about survey's topic.
about THE survey's topic

2023-07-13 19:24 UTC, fgrabowski commented on README.md
> +Typical example of a survey is when person is asked to agree with a statement with answers on a five-level scale:
A typical

2023-07-13 19:24 UTC, fgrabowski commented on README.md
> +Typical example of a survey is when person is asked to agree with a statement with answers on a five-level scale:
and also "a person"

2023-07-14 12:44 UTC, fgrabowski requested changes

2023-07-14 12:44 UTC, fgrabowski commented on README.md
> +Ordinal scale data is common. Companies and governments can quickly perform large-scale research with surveys.
I think it should be,
"Ordinal scale data ARE common"
because word "data" is plural

2023-07-14 13:09 UTC, fgrabowski approved these changes

2023-07-14 13:22 UTC, Arturstrag approved these changes

2023-07-15 10:06 UTC, merged